#!/usr/bin/env python3
"""Semantic differential: the ALU model against the hardware on random programs.

Closes the last hole. The round trip "assembler -> disassembler -> assembler" is blind to
a shared field-layout bug: both sides use the same one. Here the chain
is different and has no shared layout:

  mnemonic --[assembler]--> word --[model, written separately from RISC5.v]--> prediction
                                 --[hardware]--> result

Two things are checked:
  1. the model's prediction matches the hardware (the result AND all four flags):
     this ties the model to the machine;
  2. the model, decoding the word, names the same operation we asked the
     assembler for: this ties the assembler to the model.
Together the chain is closed: a bug in the assembler's field layout would break
item 2, a misunderstanding of the semantics would break item 1.
"""
import random, sys
sys.path.insert(0, "tools")
import asm
from alu_model import State, step, decode

REGS = list(range(1, 12))          # R12 is MT, R15 is the link: leave them alone
SEED = 20260923                    # fixed so the run is reproducible
CASES = 900

REG_OPS = ['LSL', 'ASR', 'ROR', 'AND', 'ANN', 'IOR', 'XOR',
           'ADD', 'SUB', 'ADC', 'SBC', 'MUL', 'UMUL', 'DIV', 'UDIV']
# Immediate forms: the v bit sets the fill of the upper half,
# so the sign of the number is chosen together with the form.
IMM_OPS = ['LSL', 'ASR', 'ROR', 'AND', 'ANN', 'IOR', 'XOR', 'ADD', 'SUB',
           'ADC', 'SBC', 'MUL', 'DIV', 'ADD.uv', 'SUB.uv', 'AND.uv']
MOV_FORMS = ['reg', 'imm', 'mhi', 'H', 'NZCV']


def load(rng, reg, val):
    """Load a 32-bit constant: MHI sets the upper half, IOR fills in the rest."""
    return [f"        MHI  R{reg}, 0x{(val >> 16) & 0xFFFF:04X}",
            f"        IOR  R{reg}, R{reg}, 0x{val & 0xFFFF:04X}"]


TOTAL = {"f": 0, "w": 0, "e": 0}
HEAD = None


def flush(lines, words, final=False, st=None):
    """Close the current file and start the next one: the program must not exceed ROOM.

    The model state is reset: the hardware starts each file from reset, and
    registers, flags and H are zero there. Without this, carrying C, V and H across a
    file boundary would produce false mismatches.
    """
    TOTAL["f"] += 1
    n = TOTAL["f"]
    lines.append("        HALT")
    text = "\n".join(lines) + "\n"
    path = f"tests/t1_alu_diff{n}.s"
    open(path, "w").write(text)
    n_exp = sum(1 for l in lines if l.startswith("; EXPECT"))
    TOTAL["w"] += len(words) + 1
    TOTAL["e"] += n_exp
    print(f"  {path}: {len(words)+1} words, {n_exp} checks")
    if final:
        return None, None
    if st is not None:
        st.__init__()
    return list(HEAD), []


def main():
    rng = random.Random(SEED)
    lines, st, mism = [], State(), []
    lines.append("; T1.19 — semantic differential (GENERATED by tools/gen_alu_diff.py).")
    lines.append(f"; Seed {SEED}, {CASES} cases. Expectations computed by the model tools/alu_model.py,")
    lines.append("; written from RISC5.v independently of the assembler. Result and flags are checked.")
    lines.append("")
    global HEAD
    HEAD = list(lines)

    # The program counter is 22 bits, and the program sits at ORG = 0xFFE000: from there to
    # the end of the address space exactly 2048 words fit. So we split the
    # differential into files with a margin.
    ROOM = 1980
    words = []
    def emit(text):
        w = asm.assemble("        " + text.strip() + "\n")[0][0]
        words.append(w)
        if not step(st, w):
            sys.exit(f"model does not support: {text}")
        return w

    for _ in range(CASES):
        if len(words) > ROOM:
            lines, words = flush(lines, words, st=st)
        kind = rng.choice(['reg'] * 5 + ['imm'] * 4 + ['mov'] * 2)

        if kind == 'mov':
            form = rng.choice(MOV_FORMS)
            a = rng.choice(REGS)
            if form == 'reg':
                c = rng.choice(REGS); vc = rng.getrandbits(32)
                for t in load(rng, c, vc): lines.append(t); emit(t)
                text = f"MOV  R{a}, R{c}"
            elif form == 'imm':
                n = rng.choice([rng.randint(0, 0xFFFF), rng.randint(-0x10000, -1)])
                text = f"MOV  R{a}, {n}"
            elif form == 'mhi':
                text = f"MHI  R{a}, 0x{rng.getrandbits(16):04X}"
            else:
                text = f"MOV  R{a}, {form}"
            lines.append("        " + text); emit(text)
            lines += [f"; EXPECT R{a} = 0x{st.R[a]:08X}",
                      f"; EXPECT N = {st.N}", f"; EXPECT Z = {st.Z}",
                      f"; EXPECT C = {st.C}", f"; EXPECT V = {st.V}", ""]
            continue

        if kind == 'imm':
            mn = rng.choice(IMM_OPS)
            b, a = rng.choice(REGS), rng.choice(REGS)
            vb = rng.getrandbits(32)
            if mn.endswith('.uv'):
                n = rng.randint(-0x10000, -1)       # the suffix sets v=1
            elif mn == 'DIV':
                n = rng.randint(1, 0xFFFF)          # the divider assumes y > 0
            elif mn in ('LSL', 'ASR', 'ROR'):
                n = rng.randint(0, 31)
            elif mn in ('ADC', 'SBC'):
                # the alias fixes v=0, so a negative value is unreachable:
                # that form has to be written as ADD.uv / SUB.uv
                n = rng.randint(0, 0xFFFF)
            else:
                n = rng.choice([rng.randint(0, 0xFFFF), rng.randint(-0x10000, -1)])
            for t in load(rng, b, vb): lines.append(t); emit(t)
            text = f"{mn}  R{a}, R{b}, {n}"
            lines.append("        " + text)
            w = emit(text)
            op, u, v, q, da = decode(w)
            want = {'ADC': ('ADD', 1), 'SBC': ('SUB', 1),
                    'ADD.uv': ('ADD', 1), 'SUB.uv': ('SUB', 1),
                    'AND.uv': ('AND', 1)}.get(mn, (mn, 0))
            if (op, u) != want or da != a or q != 1:
                mism.append(f"{text}: word {w:08X}, the model reads {op} u={u} "
                            f"q={q} a={da}, expected {want} q=1 a={a}")
            lines += [f"; EXPECT R{a} = 0x{st.R[a]:08X}",
                      f"; EXPECT N = {st.N}", f"; EXPECT Z = {st.Z}",
                      f"; EXPECT C = {st.C}", f"; EXPECT V = {st.V}"]
            if mn in ('MUL', 'DIV'):
                lines.append(f"; EXPECT H = 0x{st.H:08X}")
            lines.append("")
            continue

        mn = rng.choice(REG_OPS)
        b = rng.choice(REGS)
        c = rng.choice([r for r in REGS if r != b])   # distinct operand registers
        a = rng.choice(REGS)                          # the destination may coincide with either
        vb = rng.getrandbits(32)
        if mn in ('DIV', 'UDIV'):
            vc = rng.randint(1, 0x7FFFFFFF)          # the divider assumes y > 0
        else:
            vc = rng.getrandbits(32)
        for t in load(rng, b, vb): lines.append(t); emit(t)
        for t in load(rng, c, vc): lines.append(t); emit(t)
        text = f"{mn}  R{a}, R{b}, R{c}"
        lines.append("        " + text)
        w = emit(text)
        # item 2: the model, decoding the word, must name the same operation
        op, u, v, q, da = decode(w)
        want = {'ADC': ('ADD', 1), 'SBC': ('SUB', 1),
                'UMUL': ('MUL', 1), 'UDIV': ('DIV', 1)}.get(mn, (mn, 0))
        if (op, u) != want or da != a:
            mism.append(f"{text}: the assembler gave {w:08X}, the model reads "
                        f"{op} u={u} a={da}, expected {want} a={a}")
        lines += [f"; EXPECT R{a} = 0x{st.R[a]:08X}",
                  f"; EXPECT N = {st.N}", f"; EXPECT Z = {st.Z}",
                  f"; EXPECT C = {st.C}", f"; EXPECT V = {st.V}"]
        if mn in ('MUL', 'UMUL', 'DIV', 'UDIV'):
            lines.append(f"; EXPECT H = 0x{st.H:08X}")
        lines.append("")

    flush(lines, words, final=True, st=st)
    print(f"total {CASES} cases, {TOTAL['w']} words, {TOTAL['e']} checks "
          f"in {TOTAL['f']} files")
    if mism:
        print(f"❌ the assembler and the model disagree in {len(mism)} cases:")
        for m in mism[:8]: print("   ", m)
        return 1
    print("✅ the assembler and the model agree on decoding every generated word")
    return 0


if __name__ == "__main__":
    sys.exit(main())
