#!/usr/bin/env python3
"""Don't-care bit probe: every form with u=1/v=1 that the disassembler
gives no name is executed next to the base form on THE SAME operands, and
the results are compared by XOR.

If the results match, the bit really is don't-care and the word executes
as the base operation. If not, a separate instruction stands behind this encoding,
and it must be named. We assume nothing: we read the answer from the hardware.
"""
MNEMO = ['MOV','LSL','ASR','ROR','AND','ANN','IOR','XOR',
         'ADD','SUB','MUL','DIV','FAD','FSB','FML','FDV']
# op -> (low word of operand b, high, low of c, high)
INT = (0xF0F0, 0xF0F0, 0x0005, 0x0000)

# Forms where the bit MATTERS: the result differs from the base one. The values were
# measured on the hardware and pinned so that a change of behaviour does not pass silently.
#   DIV: the divider receives ~u, so u=1 is unsigned division.
#        0xF0F0F0F0 DIV 5 = 0xFCFCFCFC signed and 0x30303030 unsigned.
#   FSB: the adder receives u and v and switches to integer/float conversion mode.
#        Architecturally these forms are undefined: the compiler emits FLT and FLOOR
#        only through FAD. The values are locked as is; no meaning is attributed to them.
DIFFER = {
    (11, 1, 0): (0x30303030, "UDIV: unsigned division"),
    (11, 1, 1): (0x30303030, "UDIV: the divider ignores the v bit"),
    (13, 1, 0): (0x4B3FFFFC, "FSB.u: the adder in conversion mode"),
    (13, 0, 1): (0x00500000, "FSB.v: the same with truncation"),
    (13, 1, 1): (0x00BFFFFC, "FSB.uv"),
}
FP  = (0x0000, 0x3FC0, 0x0000, 0x4010)          # 1.5 and 2.25

def word(u, v, a, b, op, c):
    return ((u << 1 | v) << 28) | (a << 24) | (b << 20) | (op << 16) | c

out = ["; T1.17 — don't-care probe for bits u and v (GENERATED by tools/gen_dontcare_test.py).",
       "; For each form: the base one (u=0,v=0) in R3, the one under test in R4, XOR in R5.",
       "; R5 = 0 means the bit is don't-care and the word executes as the base operation.",
       ""]
n = 0
for op in (1, 2, 3, 4, 5, 6, 7, 11, 13, 14, 15):
    lo1, hi1, lo2, hi2 = FP if op >= 12 else INT
    for (u, v) in ((1, 0), (0, 1), (1, 1)):
        if op == 1 and u == 0 and v == 1:
            continue                     # this is the CHK encoding, checked separately
        out += [f"; ── {MNEMO[op]} u={u} v={v} ──",
                # MHI overwrites the whole register, so the upper half
                # is set first, and the lower half is filled in via IOR.
                f"        MHI  R1, 0x{hi1:04X}",
                f"        IOR  R1, R1, 0x{lo1:04X}",
                f"        MHI  R2, 0x{hi2:04X}",
                f"        IOR  R2, R2, 0x{lo2:04X}",
                f"        WORD 0x{word(0,0,3,1,op,2):08X}      ; {MNEMO[op]} R3, R1, R2",
                f"        WORD 0x{word(u,v,4,1,op,2):08X}      ; the same with u={u} v={v}",
                 "        XOR  R5, R3, R4"]
        key = (op, u, v)
        if key in DIFFER:
            val, why = DIFFER[key]
            out += [f"; EXPECT R4 = 0x{val:08X}   ; {why}", ""]
        else:
            out += ["; EXPECT R5 = 0", ""]
        n += 1
out.append("        HALT")
open("tests/t1_dontcare.s","w").write("\n".join(out) + "\n")
print(f"tests/t1_dontcare.s: {n} comparisons")
