import fs from 'node:fs';
import { Machine } from './machine.js';
import { OberonFS, parseRsc, readText } from './oberonfs.js';
const prom = new Uint32Array(fs.readFileSync('prom_sd.mem','utf8').trim().split('\n').map(l=>parseInt(l,16)));
const img = new Uint8Array(fs.readFileSync('oberon.dsk'));
const m = await Machine.create(prom, img);
for (let i=0;i<12;i++) m.run(1e6);
const SRC = 'MODULE\nIdx;\n  VAR a: ARRAY 100 OF INTEGER;\n  PROCEDURE Sum*(n: INTEGER): INTEGER;\n    VAR i, s: INTEGER;\n  BEGIN s := 0; i := 0;\n    WHILE i < n DO s := s + a[i]; INC(i) END;\n    RETURN s\n  END Sum;\nEND Idx.\n';
m.click(700,620,4); m.type('Edit.Open Idx.Mod ~'); m.run(2e6);
m.click(680,569,2); for(let i=0;i<8;i++) m.run(1e6);
m.click(100,60,4); m.run(500000); m.type(SRC, 6000); m.run(2e6);
m.click(345,6,2); for(let i=0;i<10;i++) m.run(1e6);
const F=()=>new OberonFS(m);
m.click(700,620,4); m.type('\nORP.Compile Idx.Mod/s ~'); m.run(2e6);
m.click(690,581,2); for(let i=0;i<25;i++) m.run(1e6);
const a=parseRsc(F().read(F().files().get('Idx.rsc')));
console.log(`with checks: ${a.codeWords} words, version ${a.version}`);
m.click(20,37,4); m.run(500000); m.type('*', 6000); m.run(1e6);
m.click(345,6,2); for(let i=0;i<8;i++) m.run(1e6);
console.log('line 2:', JSON.stringify(readText(F().read(F().files().get('Idx.Mod'))).split('\n')[1]));
m.click(690,581,2); for(let i=0;i<30;i++) m.run(1e6);
const b=parseRsc(F().read(F().files().get('Idx.rsc')));
console.log(`without checks: ${b.codeWords} words, version ${b.version}`);
console.log(`difference: ${a.codeWords-b.codeWords} words`);
