import fs from 'node:fs';
import OberonRISC5 from './risc5.js';
const prom = new Uint32Array(fs.readFileSync('prom_sd.mem','utf8').trim().split('\n').map(l=>parseInt(l,16)));
const img  = new Uint8Array(fs.readFileSync('oberon.dsk'));
const M = await OberonRISC5();
const pP = M._malloc(prom.length*4); M.HEAPU8.set(new Uint8Array(prom.buffer), pP);
const pI = M._malloc(img.length);    M.HEAPU8.set(img, pI);
M._soc_init(pP, prom.length, pI, img.length);
const t0 = performance.now();
let n = 0; for (let i=0;i<12;i++) n += M._soc_run(1000000);
const dt = (performance.now()-t0)/1000;
const fb = new Uint32Array(M.HEAPU32.buffer, M._soc_framebuffer(), M._soc_fb_words());
let crc=0; for (let k=0;k<fb.length;k++) crc=((Math.imul(crc,31)+fb[k])>>>0);
console.log(`ES module: ${n} instructions in ${dt.toFixed(2)} s = ${(M._soc_cycles()/dt/1e6).toFixed(2)} MHz-equiv`);
console.log(`screen checksum ${crc.toString(16).toUpperCase().padStart(8,'0')} (native B5DFC933)`);
