#!/usr/bin/env python3
"""Перегенерация ассемблера loop.c через CHERI Compiler Explorer (Кембридж).

Ничего ставить не надо: компиляция идёт на их сервере, запрос и ответ — JSON
(то же, что `curl -X POST .../api/compiler/<id>/compile`).

    python3 gen.py

Результат: <compiler-id>.s рядом со скриптом. В шапку каждого файла пишется
версия компилятора, которую назвал сервер, и флаги.
"""
import json
import pathlib
import sys
import urllib.request

HERE = pathlib.Path(__file__).resolve().parent
API = "https://cheri-compiler-explorer.cl.cam.ac.uk/api/compiler"
# Без развёртки и векторизации: иначе тело цикла перестаёт быть «одной индексацией».
FLAGS = "-O2 -fno-unroll-loops -fno-vectorize -fno-slp-vectorize"
TARGETS = [
    "morello-purecap",        # Morello, все указатели — капабилити
    "morello-hybrid",         # Morello, указатели обычные 64-битные
    "morello-nocheri",        # тот же компилятор, чистый AArch64
    "cheri-riscv64-purecap",  # CHERI-RISC-V 64, purecap
    "cheri-riscv64-nocheri",  # тот же компилятор, чистый RV64
]


def compile_one(cid, source):
    req = {"source": source,
           "options": {"userArguments": FLAGS,
                       "filters": {"labels": True, "directives": True,
                                   "commentOnly": True, "demangle": True,
                                   "intel": False}}}
    r = urllib.request.Request(f"{API}/{cid}/compile",
                               data=json.dumps(req).encode(),
                               headers={"Content-Type": "application/json",
                                        "Accept": "application/json"})
    with urllib.request.urlopen(r, timeout=120) as f:
        return json.load(f)


def compiler_names():
    r = urllib.request.Request(API.rsplit("/", 1)[0] + "/compilers",
                               headers={"Accept": "application/json"})
    with urllib.request.urlopen(r, timeout=60) as f:
        return {c["id"]: c["name"] for c in json.load(f)}


def main():
    source = (HERE.parent / "loop.c").read_text()
    names = compiler_names()
    for cid in TARGETS:
        resp = compile_one(cid, source)
        if resp.get("code", 0) != 0:
            err = "".join(x["text"] + "\n" for x in resp.get("stderr", []))
            sys.exit(f"{cid}: компиляция не прошла\n{err}")
        head = (f"# {cid} ({names.get(cid, '?')})\n"
                f"# flags: {FLAGS}\n"
                f"# source: ../loop.c; generated by gen.py via {API}\n")
        body = "".join(l["text"] + "\n" for l in resp["asm"])
        (HERE / f"{cid}.s").write_text(head + body)
        print(f"{cid}.s")


if __name__ == "__main__":
    main()
