#!/usr/bin/env python3
"""Builds ApplicationDefinitions for the Cozystack catalog from the repository description.

The application schema is taken not from separate text but directly from the
chart's values.schema.json: that way the catalog description cannot diverge from
what the chart actually accepts. The icon comes from the chart's file.

The chart reference name follows the platform's own rule
(internal/marketplace/naming.ArtifactName): <source>-<variant>-<component>,
with dots replaced by hyphens.
"""
import base64
import json
import pathlib
import sys

import yaml


def artifact_name(package_source: str, variant: str, component: str) -> str:
    """The Cozystack artifact naming rule, reproduced literally."""
    part = lambda s: s.replace(".", "-")
    return f"{part(package_source)}-{part(variant)}-{part(component)}"


def build(repo: pathlib.Path) -> dict[str, str]:
    spec_path = repo / "appdefs.yaml"
    spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
    packages = repo.parents[1]  # <repo>/packages/system/<x>-rd -> <repo>/packages

    out: dict[str, str] = {}
    for app in spec["apps"]:
        chart = packages / app["chartPath"]
        schema_file = chart / "values.schema.json"
        if not schema_file.is_file():
            sys.exit(f"no {schema_file}: nowhere to take the schema from")
        # The catalog schema is exactly the chart values schema, not a retelling.
        schema = json.loads(schema_file.read_text(encoding="utf-8"))

        dash = dict(app["dashboard"])
        icon_rel = dash.pop("icon", None)
        if icon_rel:
            icon_bytes = (chart / icon_rel).read_bytes()
            dash["icon"] = base64.b64encode(icon_bytes).decode("ascii")

        doc = {
            "apiVersion": "cozystack.io/v1alpha1",
            "kind": "ApplicationDefinition",
            "metadata": {"name": app["component"]},
            "spec": {
                "application": {
                    "kind": app["kind"],
                    "plural": app["plural"],
                    "singular": app["singular"],
                    "openAPISchema": json.dumps(schema, separators=(",", ":"),
                                                ensure_ascii=False),
                },
                "release": {
                    "prefix": app["prefix"],
                    "labels": {"sharding.fluxcd.io/key": "tenants"},
                    "chartRef": {
                        "kind": "ExternalArtifact",
                        "name": artifact_name(spec["packageSource"],
                                              spec["variant"],
                                              app["component"]),
                        "namespace": spec["artifactNamespace"],
                    },
                },
                "dashboard": dash,
            },
        }
        header = (
            "# Generated by tools/gen-appdefs.py from appdefs.yaml and\n"
            f"# {app['chartPath']}/values.schema.json. Do not edit by hand:\n"
            "# `make gen` overwrites it, `make check` catches a mismatch.\n"
        )
        out[f"{app['component']}.yaml"] = header + yaml.safe_dump(
            doc, allow_unicode=True, sort_keys=False, width=10**6
        )
    return out


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: gen-appdefs.py <*-rd directory>")
    repo = pathlib.Path(sys.argv[1]).resolve()
    files = build(repo)
    dest = repo / "cozyrds"
    dest.mkdir(exist_ok=True)
    for name, text in files.items():
        (dest / name).write_text(text, encoding="utf-8")
    # Stale files are not deleted: a report is more honest than silent cleanup.
    stale = sorted(p.name for p in dest.glob("*.yaml") if p.name not in files)
    for name, _ in sorted(files.items()):
        print(f"  wrote cozyrds/{name}")
    for name in stale:
        print(f"  ⚠ stale file cozyrds/{name}: appdefs.yaml does not describe it")


if __name__ == "__main__":
    main()
