#!/usr/bin/env python3
"""IDX cross-check (episode 14): QEMU with -machine oberon,chk=on,desc=on against the RTL.

The RTL here is the native Verilator model with -DWITH_DESC (impl/build/obj_desc/
run_tests_desc, the --budget mode prints all registers): there is no WASM build
of the core with descriptors, and the native one is the same RTL. Two programs:

  * tests/bench_bounds_d: the headline-number loop with IDX (finding 81);
  * tests/t3_idx_q:       40 random IDX and a random out-of-bounds access
                          (generated by tools/gen_idx_diff.py, like t3_idx_rand):
                          after the budget the machine sits in the trap handler,
                          so the trap is compared too.

Negative control: with chk=on but without desc=on the state must diverge.
The comparison over the QEMU log works as in compare_chk.py; see its caveats.
"""
import pathlib, subprocess, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from compare_chk import in_qemu, state_at, aligned, IMPL  # noqa: E402

# t3_idx_q is a short variant of t3_idx_rand (40 cases): the QEMU ROM is 512 words,
# the full file (1666 words) does not fit, and QEMU silently fails to start.
CASES = (("bench_bounds_d", 8000), ("t3_idx_q", 520))


def prepare():
    tests = IMPL / "tests"
    subprocess.run([sys.executable, str(IMPL / "tools/gen_idx_diff.py"), "40", "14",
                    str(tests / "t3_idx_q.s")], check=True, capture_output=True)
    for n in ("t3_idx_q", "bench_bounds_d"):
        subprocess.run([sys.executable, str(IMPL / "tools/asm.py"), str(tests / f"{n}.s")],
                       check=True, capture_output=True)


def in_rtl(name, budget):
    out = subprocess.run([str(IMPL / "build/obj_desc/run_tests_desc"), str(IMPL / "tests" / name),
                          f"--budget={budget}"], capture_output=True, text=True, check=True).stdout
    f = next(l for l in out.splitlines() if l.startswith("REGS")).split()
    return {"regs": [int(x, 16) for x in f[1:17]], "pc": int(f[18], 16)}


def main():
    prepare()
    bad = 0
    for name, budget in CASES:
        binp = IMPL / "tests" / f"{name}.bin"
        rtl = in_rtl(name, budget)
        blocks = in_qemu(binp, budget, chk=True, extra=",desc=on")
        idx, hits = aligned(blocks, budget, rtl["pc"])
        # After HALT (B .) the machine sits at one address, and there are several
        # records with it. That is not ambiguity if the state is the same in all.
        if idx is None and len(hits) > 1 and \
                len({tuple(state_at(blocks, k)[0]) for k in hits}) == 1:
            idx = hits[0]
        if idx is None:
            print(f"  ❌ {name}: no record with address {rtl['pc']:08X} (matching {len(hits)})")
            bad += 1; continue
        q, _ = state_at(blocks, idx)
        diff = [i for i in range(16) if q[i] != rtl["regs"][i]]
        if diff:
            for i in diff:
                print(f"  ❌ {name} R{i}: RTL {rtl['regs'][i]:08X}, QEMU {q[i]:08X}")
            bad += 1; continue
        print(f"  ✅ {name}: 16 registers match at {rtl['pc']:08X} after {budget} instructions")
        plain, _ = state_at(in_qemu(binp, budget, chk=True), idx)   # CHK on, IDX off
        if plain == rtl["regs"]:
            print(f"  ❌ {name}: same state without desc=on, so the check verifies nothing")
            bad += 1
        else:
            print(f"  ✅ {name}: without desc=on these diverge: "
                  f"{', '.join('R%d' % i for i in range(16) if plain[i] != rtl['regs'][i])}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
